spring:
  cache:
    type: redis
    redis:
      time-to-live: 60000
  application:
    name: my-app
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/mydb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
