spring:
  application:
    name: my-app
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/mydb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
